name: ujson5 Feature request
description: 'Suggest a new feature for ujson5'
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to ujson5! 🎉

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏

    validations:
      required: true
