name: benchmark

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: |
            poetry-dynamic-versioning
      - name: Check Poetry version
        run: |
          poetry --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --with dev --no-interaction
      #----------------------------------------------
      #       run test suite & publish coverage
      #----------------------------------------------

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        env:
          CI_ENV: true
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: poetry run pytest --codspeed
